import React from 'react';
import IconMoon, { type IconMoonProps } from 'react-native-icomoon';

import iconSet from './selection.json';

const IconNames = [
	'move',
	'file-doc',
	'file-img',
	'file-pdf',
	'file-rar',
	'file-xls',
	'file-zip',
	'add-document',
	'check-circle-fill',
	'copy',
	'email-marketing',
	'like',
	'schedule',
	'tag',
	'uncheck-circle',
	'save',
	'upload-template',
	'gantt',
	'view-off',
	'view-on',
	'warning-triangle',
	'more-verticel',
	'down',
	'minus',
	'plus',
	'hv-add',
	'rs-add',
	'info',
	'nav',
	'arrow-bold-left',
	'arrow-bold-right',
	'pen',
	'refresh',
	'close',
	'question-circle',
	'question',
	'accounting-module',
	'attach-italic',
	'bag',
	'bell',
	'bizcore-module',
	'calendar',
	'checkbox-circle-bottom',
	'close-circle',
	'dashboard',
	'database',
	'download-template',
	'filter',
	'gift-add',
	'gift',
	'hcm-module',
	'hv-accept',
	'hv-cancel',
	'hv-config',
	'hv-delete',
	'hv-edit',
	'hv-send-mail',
	'image-add',
	'image',
	'key-horizontal',
	'key-itatic',
	'left',
	'lock',
	'login',
	'logout',
	'purchase-module',
	'right',
	'rs-collapse',
	'rs-delete',
	'rs-expand',
	'sale-module',
	'search',
	'setting',
	'sider-collapse',
	'sider-expand',
	'unlock',
	'up',
	'update',
	'user',
	'warehouse-module',
	'world',
	'youtube',
] as const;

type IconProps = {
	disabled?: boolean;
	name: (typeof IconNames)[number];
} & Omit<IconMoonProps, 'iconSet'>;

const Icon = ({ name, ...restProps }: IconProps) => {
	return <IconMoon iconSet={iconSet} name={name} {...restProps} />;
};

export default Icon;
